<section class="section">
    <div class="container">
        <div class="row-fluid">
            <div class="span12">
                <article class="blog-post">
                    <header class="blog-header">
                        <h2>
                            The History of ExtraContent <small>by Adam Merrifield, 6 Sep 2012.</small>
                        </h2>
                    </header>
                    <p>ExtraContent came about in 2008 when a handful of 3rd party developers addressed the need for more content spaces in RapidWeaver. While the content area and sidebar were ample space for many RapidWeaver users, there were many more who wanted the flexibility to add web content outside of the main page and sidebar areas in ways keeping with todays modern web designs.</p>

                    <p>ExtraContent was the solution agreed upon by these developers as an easy means of end users adding more content to their site in developer designated areas of ExtraContent enabled themes. While these areas will vary from theme to theme, the process will be very much the same. These developers worked closely to come up with a solution that would give all users a common experience. And thus the Developer Standard for ExtraContent was born.</p>

                    <p>ExtraContent is supported by nearly all 3rd party RapidWeaver themes and is still one of the most sought after features after all of these years. The uses for ExtraContent are as unique and varied as the individuals using them. From auxiliary navigation areas, to video playback boxes, from mastheads to jumbo footers, your imagination is the only limit to what you can use ExtraContent for.</p>

                    <p>Today, the ExtraContent source code is largely maintained by myself, Adam Merrifield, with support and contributions from other developers (listed in the ExtraContent source code) as ExtraContent grows and improves year over year.</p>

                    <h3>
                        Remember this one?
                    </h3>
                    <p>When we first launched ExtraContent, we created this well-intentioned, yet somewhat awkward video, starring Alex the ExtraContent Android. We'll preserve it here for posterity.</p>
                    <div class="frame"><div class="flex-video vimeo hddisplay"><iframe src="http://player.vimeo.com/video/2730319" width="500" height="313" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div>
                </article>
            </div>    
        </div>
    </div>
</section>