<section class="section">
    <div class="container">
        <div class="row-fluid">
            <div class="span12">
                <article class="blog-post">
                    <header class="blog-header">
                        <h2>
                            Using the ExtraContent Stack <small>by Adam Merrifield, 6 Sep 2012.</small><a href="https://github.com/downloads/seyDoggy/ExtraContent/ExtraContent-add-ons.zip" class="btn btn-primary pull-right" style="color:white;text-transform: none;">Download</a>
                        </h2>
                    </header>
                    <div class="frame"><div class="flex-video vimeo hddisplay"><iframe src="http://player.vimeo.com/video/49029833" width="500" height="313" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div>
                    <ol>
                        <li><p>Download and install the <a href="https://github.com/downloads/seyDoggy/ExtraContent/ExtraContent-add-ons.zip" title="ExtraContent Snippets and stacks">ExtraContent add-ons</a>.</p></li>
                        <li><p>Open the Stack element panel.</p></li>
                        <li><p>Search for "ExtraContent" in the panel's search field.</p></li>
                        <li><p>Drag the ExtraContent stack on your page.</p></li>
                        <li><p>Change the ExtraContent value in the settings.</p></li>
                        <li><p>Add more stacks inside the ExtraContent stack and preview.</p></li>
                        <li><p>Depending on your theme, your ExtraContent may now automatically appear, or there might be an option to turn the ExtraContent on or off.</p></li>
                        <li><p>To add more content to more areas, simply repeat steps 1 through 6.</p></li>
                </article>

            </div>    
        </div>
    </div>
</section>