<footer  id="footer" role="contentinfo" class="section">
    <div class="container">
        <div class="row-fluid">
            <div class="span6">
                <h3><i class="icon-github-sign"></i> Github projects (developer links)</h3>
                <ul class="unstyled">
                    <li>
                        <h4><a href="https://github.com/seyDoggy/SeydoggySlideshow" title="SS3 on github">SeydoggySlideshow:</a> <small>Advanced, integrated "anything" slider for RapidWeaver<sup>&reg;</sup>.</small></h4>
                    </li>
                    <li>
                        <h4><a href="https://github.com/seyDoggy/ExtraContent" title="ExtraContent on github">ExtraContent:</a> <small>Put anything anywhere in your next RapidWeaver<sup>&reg;</sup> theme.</small></h4>
                    </li>
                    <li>
                        <h4><a href="https://github.com/seyDoggy/sdSmartNav" title="sdSmartNav on github">sdSmartNav:</a> <small>Multi-option, tiered navigation with drop menus for RapidWeaver<sup>&reg;</sup>.</small></h4>
                    </li>
                    <li>
                        <h4><a href="https://github.com/seyDoggy/sdLightboxAlbums" title="sdLightboxAlbums on github">sdLightboxAlbums:</a> <small>A clean, out of the way lightbox for RapidWeaver<sup>&reg;</sup> album pages.</small></h4>
                    </li>
                    <li>
                        <h4><a href="https://github.com/seyDoggy/RwSetGet" title="RwSetGet on github">RwSetGet:</a> <small>An indispensable JavaScript tool for RW's base_url and pathto syntax.</small></h4>
                    </li>
                </ul>
            </div>
            
            <div class="span3">
                <h3><i class="icon-globe"></i> Other Links</h3>
                <ul class="unstyled">
                    <li>
                        <h4><a href="http://seydesign.com" title="seydesign, Professional RapidWeaver<sup>&reg;</sup> themes">seydesign.com</a></h4>
                    </li>
                    <li>
                        <h4><a href="http://seydoggy.com" title="seydoggy company site">seydoggy.com</a></h4>
                    </li>
                    <li>
                        <h4><a href="http://adam.merrifield.ca" title="adam merrifield's blog">adam.merrifield.ca</a></h4>
                    </li>
                    <li>
                        <h4><a href="https://twitter.com/seyDoggy" title="seydoggy on twitter">@seyDoggy</a></h4>
                    </li>
                    <li>
                        <h4><a href="https://twitter.com/seyDesign" title="seydesign on twitter">@seyDesign</a></h4>
                    </li>
                </ul>
            </div>

            <div class="span3">
                <p><small>&copy; 2012 seyDoggy</small></p>
                <p><small>RapidWeaver<sup>&reg;</sup> is a registered trademark of <a href="http://realmacsoftware.com" title="Realmac Software">Realmac Software</a>.</small></p>
            </div>
        </div>
    </div>
</footer>