<section id="promo" class="section alt">
    <div class="container">
        <div class="row-fluid">
            <div class="span7">
                <div class="hero-unit">
                    <h1>Building tools for the greater good of RapidWeaver<sup>&reg;</sup>.</h1>
                    <p>We've been a part of the RapidWeaver<sup>&reg;</sup> ecosystem for over 7 years. In that time we've shared a lot of what we've earned back to the other developers and the community as a whole.</p>
                    <p>Stand on the shoulders of giants, as they say — learn from what we've accomplished already and get the higher perspective.</p>
                </div>
            </div>
            <div class="span5 pull-right">
                <img src="img/assets/RapidWeaver5.png" alt="RapidWeaver<sup>&reg;</sup>">
            </div>
        </div>
        <div id="myCarousel" class="carousel slide">
            <!-- Carousel items -->
            <div class="carousel-inner">
                <div class="active item">
                    <div class="page-header">
                        <h3>For RapidWeaver<sup>&reg;</sup> Users <small>get up and running quickly with simple how-to's</small></h3>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="well">
                                <h3><a href="?p=ExtraContent" title="Learn more about ExtraContent">Using ExtraContent</a></h3>
                                <p>First introduced in 2008, ExtraContent has become a staple in RapidWeaver<sup>&reg;</sup> themes, moving RapidWeaver<sup>&reg;</sup> beyond the old idea of a sidebar/content layouts. <a href="?p=ExtraContent" title="Learn more about ExtraContent"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="well">
                                <h3><a href="?p=SS3" title="Learn more about SS3">Using SS3</a></h3>
                                <p>The most advanced, integrated "anything" slide show in RapidWeaver<sup>&reg;</sup>. SS3 lets you create sliders from built-in images, remotely hosted images, content from stacks, snippets and more. <a href="?p=SS3" title="Learn more about SS3"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="page-header">
                        <h3>For RapidWeaver<sup>&reg;</sup> Developers <small>give your customers the features they want</small></h3>
                    </div>
                    <div class="row-fluid">
                        <div class="span3">
                            <div class="well">
                                <h3><a href="https://github.com/seyDoggy/SeydoggySlideshow" title="SS3 on github">sdSlideshow (SS3)</a></h3>
                                <p>The most advanced, integrated "anything" slide show in RapidWeaver<sup>&reg;</sup>. <a href="?p=SS3" title="Learn more about SS3"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="well">
                                <h3><a href="https://github.com/seyDoggy/ExtraContent" title="ExtraContent on github">ExtraContent (EC)</a></h3>
                                <p>Put anything anywhere in your next RapidWeaver<sup>&reg;</sup> theme. <a href="?p=ExtraContent" title="Learn more about ExtraContent"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="well">
                                <h3><a href="https://github.com/seyDoggy/sdSmartNav" title="sdSmartNav on github">sdSmartNav</a></h3>
                                <p>Multi-option, tiered navigation with drop menus for RapidWeaver<sup>&reg;</sup>. <a href="?p=SS3" title="Learn more about SS3"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                        <div class="span3">
                            <div class="well">
                                <h3><a href="https://github.com/seyDoggy/RwSetGet" title="RwSetGet on github">RwSetGet</a></h3>
                                <p>An indispensable JavaScript tool for RW's base_url and pathto syntax. <a href="?p=SS3" title="Learn more about SS3"><i class="icon-arrow-right"></i></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- Carousel nav -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a> <a class="carousel-control right" href="#myCarousel" data-slide="next">›</a>
        </div>    
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="page-header">
            <h1>Who are we? <small>seyDoggy FOSS (Free and Open-Source Software)</small></h1>
        </div>
        <div class="row-fluid">
            <ul class="thumbnails bordered">
                <li class="span4">
                    <h3>We code</h3>
                    <p>Since 2005 we have developed web <a href="http://seydesign.com/" title="Professional RapidWeaver<sup>&reg;</sup> themes and stacks by seyDesign">themes and stacks</a> for the ever touted <a href="http://www.realmacsoftware.com/RapidWeaver<sup>&reg;</sup>/" title="RapidWeaver<sup>&reg;</sup> 4 - Powerful Web Design Software for Mac OS X">RapidWeaver<sup>&reg;</sup></a> web authoring app. From <a href="http://en.wikipedia.org/wiki/Applescript" title="AppleScript - Wikipedia, the free encyclopedia">AppleScript</a> to <a href="http://en.wikipedia.org/wiki/Xhtml" title="XHTML - Wikipedia, the free encyclopedia">XHTML</a>, we love it all. Keep in check with our <a href="http://adam.merrifield.ca/category/geeky/" title="Adam Merrifield { the collective  - the collective thoughts and web works of adam merrifield}">code trials here</a>.</p>
                </li>
                <li class="span4">
                    <h3>We share</h3>
                    <p>We are learning all the time, learning from those who have been gracious enough to share with us. To pay it forward, we promote learning through our blog, <a href="https://github.com/" title="GitHub - Social Coding">github</a> or <a href="http://www.meetup.com/kw-design-dev-meetup/" title="#kwdm">#kwdm</a>.</p>
                </li>
                <li class="span4">
                    <h3>We grow</h3>
                    <p>Coding isn't all we do. We also design, photograph, write and embark on anything entrepreneurial. Have an idea you think we'd be interested in? <a href="https://twitter.com/seyDoggy" title="Contact us">Contact us</a> and let us know.</p>
                </li>
            </ul>
        </div>
    </div>
</section>