<section class="section">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <article class="blog-post">
                    <header class="blog-header">
                        <h2>
                            SlideBox Stack <small>by Adam Merrifield, 11 Sep 2012.</small><a href="http://seydesign.com/downloads/stacks/seyDoggy-SlideBox.dmg" class="btn btn-primary pull-right" style="color:white;text-transform: none;">Download</a>
                        </h2>
                    </header>
                    <div class="frame"><div class="flex-video vimeo hddisplay"><iframe src="http://player.vimeo.com/video/26633826" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div>
                    <p>SlideBox is a simple, effective stack that allows you to create a content-rich slide show in any SeydoggySlideshow 3 (or SS3) enabled theme. From simple text and images or anything you can imagine, your SS3 enabled theme will turn each box into it's own slide.</p>

                    <p>Using the built-in slide show controls in your SS3 enabled theme, you can add flare to your content slide show with speed settings, delays and special effects. Or take it a step further and use the advanced tricks in the SS3 User API to link each slide to another destination.</p>

                    <h3>Instructions</h3>

                    <ol>
                        <li><p>Download and install the <a href="http://seydesign.com/downloads/stacks/seyDoggy-SlideBox.dmg" title="SlideBox stack">SlideBox stack</a>.</p></li>
                        <li><p>Drag a SlideBox stack from your Stacks Library onto your Stacks page.</p></li>
                        <li><p>Drag other stacks into each available content space and propagate each item with text and media as needed.</p></li>
                        <li><p>To add or remove items from your slide show, open the SlideBox stacks HUD and select the number of items you want in your slide show.</p></li>
                        <li><p>Refer to your themes <em>Styles</em> panel for further settings.</p></li>
                    </ol>
                </article>
            </div>    
        </div>
    </div>
</section>