<section class="section">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <article class="blog-post">
                    <header class="blog-header">
                        <h2>
                            Basic features of SS3 <small>by Adam Merrifield, 11 Sep 2012.</small>
                        </h2>
                    </header>

                    <p><strong>Note:</strong> All of these basic features can be found in the RapidWeaver Page Inspector under the Styles tab.</p>

                    <ol class="bordered">
                        <li>
                            <h4>Height (header/slide show)</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>An SS3 enabled theme will likely have the option to set a header height. If using background images, simply chose a height that works best.</p>
                                    <p>When working with more engaging content, such text, text and images or stacks, it's likely best to use the variable height settings. The height will adjust to fit your content.</p>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-height.png" class="pull-center" alt="header height"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Background (header/slide show)</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>If you are not using SS3 or are using SS3 to rotate through content based slides, the background will serve as a backdrop to your slide show or ExtraContent. Otherwise, if you are using SS3 to rotate through built-in images, you can ignore this option.</p>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-background.png" class="pull-center" alt="header height"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Slide show type</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>The slide show type allows you to choose from Off, Content or a selection of preset internal sequences.</p>
                                    <ul>
                                        <li><p><strong>Off / Manual (snippet)</strong> - turns off the slide show unless the <a href="?p=SS3&s=SlideNum#section" title="SlideNum">SlideNum</a> or <a href="?p=SS3&s=SlideWH#section" title="SlideWH">SlideWH</a> snippets are detected.</p></li>
                                        <li><p><strong>Content (SlideBox snippet/stack)</strong> - enables the use of content slides created either with the <a href="?p=SS3&s=SlideBox snippet#section" title="SlideBox snippet">SlideBox snippet</a> or <a href="?p=SS3&s=SlideBox stack#section" title="SlideBox stack">SlideBox stack</a>.</p></li>
                                        <li><p><strong>Slides X to Y</strong> - enables the internal slide sequence using slides X (number representing starting slide) to Y (number representing ending slide).</p></li>
                                    </ul>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-type.png" class="pull-center" alt="slide show type"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Slide show timeout</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>Slide show timeout allows you to select the duration that any given slide in the sequence will be shown for, from a minimum of 4 seconds to a maximum to 20 seconds.</p>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-timeout.png" class="pull-center" alt="slide show timeout"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Slide show effect</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>Slide show effect allows you to choose from an assortment of transition animations that determine the how one slide will switch to the next.</p>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-effect.png" class="pull-center" alt="slide show effect"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Slide show speed</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>Slide show speed controls the amount of time a transition takes. The shorter the time, the faster the animation is that switches one slide to the next.</p>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-speed.png" class="pull-center" alt="slide show speed"></div> 
                                </div>
                            </div>
                        </li>
                        <li>
                            <h4>Slide show settings</h4>
                            <div class="row-fluid">
                                <div class="span8">
                                    <p>Slide show settings are a collection of additional features that you can enable individually or en masse.</p>
                                    <ul>
                                        <li><p><strong>Auto stop</strong> - automatically stops the slide show once the last slide has been reached.</p></li>
                                        <li><p><strong>Navigation</strong> - displays left and right navigation arrows at either side of each slide.</p></li>
                                        <li><p><strong>Pager</strong> - displays pager buttons at the bottom of each slide.</p></li>
                                        <li><p><strong>Pause on hover</strong> - causes the slide show to pause the slide show when hovered over.</p></li>
                                        <li><p><strong>Random order</strong> - displays the slides in random order.</p></li>
                                    </ul>
                                </div>
                                <div class="span4">
                                    <div class="frame"><img src="img/assets/ss3-settings.png" class="pull-center" alt="slide show settings"></div> 
                                </div>
                            </div>
                        </li>
                    </ol>
                </article>
            </div>    
        </div>
    </div>
</section>